devlopment: &non_production_settings
  :itunes:
    :path: "~/Music/iTunes"

  :plex:
    :host: "127.0.0.1"
    :port: 32400

test:
  <<: *non_production_settings

production:
  :itunes:
    :path: "~/Music/iTunes"

  :plex:
    :host: "127.0.0.1"
    :port: 32400